//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainStorm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\jett2\\\\Downloads\\\\carnegie mellon\\\\research\\\\surg fall 2020\\\\brainStor" +
            "m\\\\BrainStorm C#\\\\BrainStorm\\\\sessions\\\\")]
        public string BasePath {
            get {
                return ((string)(this["BasePath"]));
            }
            set {
                this["BasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!!242prank1sonyou")]
        public string EmailPassword {
            get {
                return ((string)(this["EmailPassword"]));
            }
            set {
                this["EmailPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jett2.718hays@gmail.com")]
        public string EmailAddress {
            get {
                return ((string)(this["EmailAddress"]));
            }
            set {
                this["EmailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HmCIyDZbV4iuNsJqug0GkbBKgMYwfIvzf5sXxgoQ")]
        public string EmotivID {
            get {
                return ((string)(this["EmotivID"]));
            }
            set {
                this["EmotivID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HxHdQGmJqJmO5sHI2rvh11eGDyaXDCNe4BeqSaWVnDuuaT5bajYwXsZwcNb5l6zmq5xsaFq65wGjnYKKI" +
            "dOgjEk6bo8IzJTgSSDI3nw34bnca7hfnD14z6jQBApIr5WY")]
        public string EmotivSecret {
            get {
                return ((string)(this["EmotivSecret"]));
            }
            set {
                this["EmotivSecret"] = value;
            }
        }
    }
}
